### PR TITLE
some tests for cached behaviour

### PR DESCRIPTION
**Pull request by varjagg**

### CODE REVIEW

**Comment by slyrus** [comment]
I get the following error when I run your tests:

```
; /Users/sly/.cache/common-lisp/sbcl-1.3.16.18-5db73e640-macosx-x64/Users/sly/projects/cl-jpeg-tests/cl-jpeg-tests-TMP.fasl written
; compilation finished in 0:00:00.090
; in: ALEXANDRIA.0.DEV:NAMED-LAMBDA %TEST-READ-WITH-CACHED-SOURCE-TWICE
;     (LET* ((CL-JPEG-TESTS::FILE (CL-JPEG-TESTS::TEST-IMAGE "truck.jpeg"))
;            (CL-JPEG-TESTS::DESCRIPTOR (JPEG:MAKE-DESCRIPTOR))
;            (CL-JPEG-TESTS::IMG
;             (WITH-OPEN-FILE
;                 (CL-JPEG-TESTS::IN CL-JPEG-TESTS::FILE :DIRECTION :INPUT
;                  :ELEMENT-TYPE '#)
;               (JPEG:DECODE-STREAM CL-JPEG-TESTS::IN :DESCRIPTOR
;                                   CL-JPEG-TESTS::DESCRIPTOR :CACHED-SOURCE-P T)))
;            (CL-JPEG-TESTS::D1
;             (JPEG:DESCRIPTOR-SOURCE-CACHE CL-JPEG-TESTS::DESCRIPTOR)))
;       (WITH-OPEN-FILE
;           (CL-JPEG-TESTS::IN CL-JPEG-TESTS::FILE :DIRECTION :INPUT :ELEMENT-TYPE
;            '(UNSIGNED-BYTE 8))
;         (JPEG:DECODE-STREAM CL-JPEG-TESTS::IN :DESCRIPTOR
;                             CL-JPEG-TESTS::DESCRIPTOR :CACHED-SOURCE-P T))
;       (IT.BESE.FIVEAM:IS
;        (EQL CL-JPEG-TESTS::D1
;             (JPEG:DESCRIPTOR-SOURCE-CACHE CL-JPEG-TESTS::DESCRIPTOR))))
; 
; caught STYLE-WARNING:
;   The variable IMG is defined but never used.

Running test suite CL-JPEG
 Running test READ-8-BIT-GRAY ..
 Running test WRITE-8-BIT-GRAY ....
 Running test READ-8-BIT-RGB ..
 Running test WRITE-8-BIT-RGB ....
 Running test READ-WITH-CACHED-SOURCE ..
 Running test READ-WITH-CACHED-SOURCE-TWICE X
 Running test READ-WITH-SUPPLIED-CACHED-SOURCE X
 Did 16 checks.
    Pass: 14 (87%)
    Skip: 0 ( 0%)
    Fail: 2 (12%)

 Failure Details:
 --------------------------------
 READ-WITH-SUPPLIED-CACHED-SOURCE []: 
      Unexpected Error: #<JPEG-DECODER-ERROR {1003FC70E3}>
Condition JPEG:JPEG-DECODER-ERROR was signalled...
 --------------------------------
 --------------------------------
 READ-WITH-CACHED-SOURCE-TWICE []: 
      Unexpected Error: #<JPEG-DECODER-ERROR {1003FC10B3}>
Condition JPEG:JPEG-DECODER-ERROR was signalled...
 --------------------------------
```

I'm happy to have (currently) failing tests in here, but I wanted to make sure this is the expected behavior before merging.

**Comment by varjagg** [comment]
Wokrs for me: 

CL-USER> (fiveam:run-all-tests)

Running test suite CL-JPEG
 Running test READ-8-BIT-GRAY ..
 Running test WRITE-8-BIT-GRAY ....
 Running test READ-8-BIT-RGB ..
 Running test WRITE-8-BIT-RGB ....
 Running test READ-WITH-CACHED-SOURCE ..
 Running test READ-WITH-CACHED-SOURCE-TWICE .
 Running test READ-WITH-SUPPLIED-CACHED-SOURCE ..
 Did 17 checks.
    Pass: 17 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)

So I guess we need to find out the difference between our tested code. I used git master of CL-JPEG with the last PR still not merged.

**Comment by slyrus** [comment]
Ok, looks like I broke something in my PR...

**Comment by varjagg** [comment]
The library allows the jpeg to be read into cache buffer that is allocated externally once and then re-used. Some implementations have slower read-byte due to underlying gray-streams, so on things like video decoding having a reusable cache speed things up considerably.

Anyway, makes me appreciate your test suite even more!

**Comment by slyrus** [comment]
Yes, I get that :) Some thoughts though:

1. Even without reusing the buffer, it might be a win on some lisps to just read the whole file into memory and then decode that buffer.

2. All cached-source-p does is change the descriptor-byte-reader. It seems a bit weird that to get the desired functionality we need to set the source-cache and use the cached-source-p keyword. Mightn't we want to expose a new exposed function like decode-stream-with-cache or something? There's some cleanup that could be done here, but I haven't found a nice way to clean this up yet.

**Pull request merged**
